version: "3.9"
services:
    backend:
        build:
            context: ./back
        ports:
            - "4000:8080"
        depends_on:
            - "mydb"

    mydb:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
