version: "3.9"
services:
    backend:
        build:
            context: ./back
        ports:
            - "8080:8080"
        depends_on:
            - "mydb"

    mydb:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres

    adminer:
        image: adminer
        restart: always
        depends_on:
            - "mydb"
        ports:
            - 5432:8080
